# Generated by Django 3.2.7 on 2021-11-21 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonaCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoDocumento', models.CharField(max_length=2)),
                ('numeroDocumento', models.IntegerField()),
                ('nombre', models.CharField(max_length=64)),
                ('sexo', models.CharField(max_length=15)),
                ('edad', models.IntegerField()),
            ],
        ),
    ]
