# Generated by Django 3.2.7 on 2021-11-21 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personacliente',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
